name: Modify File Daily

# Exécuter tous les jours à minuit et une minute UTC
on:
  schedule:
    - cron: "1 0 * * *"

# on:
#   push:
#     branches:
#       - main  # Remplacez 'main' par le nom de votre branche principale

jobs:
  modify-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run script
        run: node ./display_date.js